import type { Metadata } from "next";
import { Dancing_Script, Nunito_Sans, Inconsolata, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const dancing = Dancing_Script({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  variable: "--font-dancing",
});

export const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800","900"],
  style: ["normal","italic"],
  variable: "--font-nunito",
});

export const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800","900"],
  style: ["normal"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${dancing.variable} ${nunito.variable} ${inconsolata.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
